# Generated by Django 5.2.10 on 2026-01-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_active_alter_bid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='active',
            new_name='is_active',
        ),
    ]
