# Generated by Django 5.2.10 on 2026-01-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auction_image_auction_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.URLField(default='https://shorturl.at/Tuo6N'),
        ),
    ]
